### ISSUE TITLE
Intermittent error during scanning - TypeError: 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by larsyngvelundin** [jacksmithinsulander/rsab#127]
Intermittently when trying to iterate over any found pools, we get this error:

```
Traceback (most recent call last):
  File "C:\Users\nok13\Documents\GitHub\WAGMI\main.py", line 100, in <module>
    start_scanner()
  File "C:\Users\nok13\Documents\GitHub\WAGMI\main.py", line 37, in start_scanner
    scanner.start()
  File "C:\Users\nok13\Documents\GitHub\WAGMI\modules\scanner\scanner_main.py", line 60, in start
    for pool in latest_pools:
TypeError: 'NoneType' object is not iterable
```

Part where it originates in our code seems to be `for pool in latest_pools:`, line 60, in scanner_main.py

**Comment by larsyngvelundin** [comment]
Quick-fix implemented in #129 PR
